Unit Model.Customer.Customer;

Interface

Uses
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    System.Generics.Collections;

Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('customer_customer')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TCustomer_Customer = Class(TMVCActiveRecord)
    Private
        [MVCTableField('CustomerID', [foPrimaryKey, foAutoGenerated])]
        FCustomerID: Int64;

        [MVCTableField('FirstName')]
        FFirstName: NullableString;

        [MVCTableField('LastName')]
        FLastName: NullableString;

        [MVCTableField('Phone')]
        FPhone: NullableString;

        [MVCTableField('NationalID')]
        FNationalID: NullableString;

        [MVCTableField('Email')]
        FEmail: NullableString;

        [MVCTableField('Address')]
        FAddress: NullableString;

        [MVCTableField('Budget')]
        FBudget: NullableDouble;

        [MVCTableField('CampaignID')]
        FCampaignID: NullableInt32;

        [MVCTableField('CreatedByUserID')]
        FCreatedByUserID: NullableInt32;

        [MVCTableField('CreatedAt', [foReadOnly])]
        FCreatedAt: NullableTDateTime;

        [MVCTableField('UpdatedAt', [foReadOnly])]
        FUpdatedAt: NullableTDateTime;

        [MVCTableField('IsActive')]
        FIsActive: NullableBoolean;

        [MVCTableField('IsSystemic', [foReadOnly])]
        FIsSystemic: NullableBoolean;

        [MVCTableField('Description')]
        FDescription: NullableString;

    Public
        Property CustomerID: Int64 Read FCustomerID Write FCustomerID;
        Property FirstName: NullableString Read FFirstName Write FFirstName;
        Property LastName: NullableString Read FLastName Write FLastName;
        Property Phone: NullableString Read FPhone Write FPhone;
        Property NationalID: NullableString Read FNationalID Write FNationalID;
        Property Email: NullableString Read FEmail Write FEmail;
        Property Address: NullableString Read FAddress Write FAddress;
        Property Budget: NullableDouble Read FBudget Write FBudget;
        Property CampaignID: NullableInt32 Read FCampaignID Write FCampaignID;
        Property CreatedByUserID: NullableInt32 Read FCreatedByUserID Write FCreatedByUserID;
        Property CreatedAt: NullableTDateTime Read FCreatedAt Write FCreatedAt;
        Property UpdatedAt: NullableTDateTime Read FUpdatedAt Write FUpdatedAt;
        Property IsActive: NullableBoolean Read FIsActive Write FIsActive;
        Property IsSystemic: NullableBoolean Read FIsSystemic Write FIsSystemic;
        Property Description: NullableString Read FDescription Write FDescription;
    End;

Implementation

End.
