Unit Model.Customer;

Interface

Uses
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    MVCFramework.ActiveRecord;

Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('customers')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TCustomer = Class(TMVCActiveRecord)
    Private
        [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
        fID: Int32;

        [MVCTableField('first_name')]
        fFirstName: NullableString;

        [MVCTableField('last_name')]
        fLastName: NullableString;

        [MVCTableField('phone')]
        fPhone: NullableString;

        [MVCTableField('national_id')]
        fNationalID: NullableString;

        [MVCTableField('email')]
        fEmail: NullableString;

        [MVCTableField('address')]
        fAddress: NullableString;

        [MVCTableField('desired_car_id')]
        fDesiredCarID: NullableInt32;

        [MVCTableField('budget')]
        fBudget: NullableCurrency;

        [MVCTableField('branch_id')]
        fBranchID: NullableInt32;

        [MVCTableField('assigned_to')]
        fAssignedTo: NullableInt32;

        [MVCTableField('status_id')]
        fStatusID: NullableInt32;

        [MVCTableField('potential_level_id')]
        fPotentialLevelID: NullableInt32;

        [MVCTableField('contact_source_id')]
        fContactSourceID: NullableInt32;

        [MVCTableField('campaign_id')]
        fCampaignID: NullableInt32;

        [MVCTableField('notes')]
        fNotes: NullableString;

        [MVCTableField('created_by')]
        fCreatedBy: NullableInt32;

        [MVCTableField('created_at', [foReadOnly])]
        fCreatedAt: NullableString;

        [MVCTableField('updated_at', [foReadOnly])]
        fUpdatedAt: NullableString;

    Public
        property ID: Int32 read fID write fID;
        property FirstName: NullableString read fFirstName write fFirstName;
        property LastName: NullableString read fLastName write fLastName;
        property Phone: NullableString read fPhone write fPhone;
        property NationalID: NullableString read fNationalID write fNationalID;
        property Email: NullableString read fEmail write fEmail;
        property Address: NullableString read fAddress write fAddress;
        property DesiredCarID: NullableInt32 read fDesiredCarID write fDesiredCarID;
        property Budget: NullableCurrency read fBudget write fBudget;
        property BranchID: NullableInt32 read fBranchID write fBranchID;
        property AssignedTo: NullableInt32 read fAssignedTo write fAssignedTo;
        property StatusID: NullableInt32 read fStatusID write fStatusID;
        property PotentialLevelID: NullableInt32 read fPotentialLevelID write fPotentialLevelID;
        property ContactSourceID: NullableInt32 read fContactSourceID write fContactSourceID;
        property CampaignID: NullableInt32 read fCampaignID write fCampaignID;
        property Notes: NullableString read fNotes write fNotes;
        property CreatedBy: NullableInt32 read fCreatedBy write fCreatedBy;
        property CreatedAt: NullableString read fCreatedAt write fCreatedAt;
        property UpdatedAt: NullableString read fUpdatedAt write fUpdatedAt;
    End;

Implementation

End.
