Unit Model.Car.Car;

Interface

Uses
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    System.Generics.Collections;

Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('car_car')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TCar_Car = Class(TMVCActiveRecord)
    Private
        [MVCTableField('CarID', [foPrimaryKey, foAutoGenerated, foReadOnly])]
        FCarID: Int32;

        [MVCTableField('Code')]
        FCode: NullableString;

        [MVCTableField('MainName')]
        FMainName: String;

        [MVCTableField('SecondName')]
        FSecondName: NullableString;

        [MVCTableField('CompanyID')]
        FCompanyID: NullableInt32;

        [MVCTableField('CategoryID')]
        FCategoryID: NullableInt32;

        [MVCTableField('Year')]
        FYear: NullableInt32;

        [MVCTableField('FuelType')]
        FFuelType: NullableString;

        [MVCTableField('Transmission')]
        FTransmission: NullableString;

        [MVCTableField('EngineCapacity')]
        FEngineCapacity: NullableDouble;

        [MVCTableField('HorsePower')]
        FHorsePower: NullableInt32;

        [MVCTableField('Torque')]
        FTorque: NullableInt32;

        [MVCTableField('Seats')]
        FSeats: NullableInt32;

        [MVCTableField('DriveType')]
        FDriveType: NullableString;

        [MVCTableField('BodyType')]
        FBodyType: NullableString;

        [MVCTableField('RangeKM')]
        FRangeKM: NullableInt32;

        [MVCTableField('SafetyRating')]
        FSafetyRating: NullableString;

        [MVCTableField('BasePrice')]
        FBasePrice: NullableDouble;

        [MVCTableField('IsActive')]
        FIsActive: NullableBoolean;

        [MVCTableField('IsSystemic')]
        FIsSystemic: NullableBoolean;

        [MVCTableField('Description')]
        FDescription: NullableString;

        [MVCTableField('CreatedAt', [foReadOnly])]
        FCreatedAt: NullableTDateTime;

    Public
        Property CarID: Int32 Read FCarID Write FCarID;
        Property Code: NullableString Read FCode Write FCode;
        Property MainName: String Read FMainName Write FMainName;
        Property SecondName: NullableString Read FSecondName Write FSecondName;
        Property CompanyID: NullableInt32 Read FCompanyID Write FCompanyID;
        Property CategoryID: NullableInt32 Read FCategoryID Write FCategoryID;
        Property Year: NullableInt32 Read FYear Write FYear;
        Property FuelType: NullableString Read FFuelType Write FFuelType;
        Property Transmission: NullableString Read FTransmission Write FTransmission;
        Property EngineCapacity: NullableDouble Read FEngineCapacity Write FEngineCapacity;
        Property HorsePower: NullableInt32 Read FHorsePower Write FHorsePower;
        Property Torque: NullableInt32 Read FTorque Write FTorque;
        Property Seats: NullableInt32 Read FSeats Write FSeats;
        Property DriveType: NullableString Read FDriveType Write FDriveType;
        Property BodyType: NullableString Read FBodyType Write FBodyType;
        Property RangeKM: NullableInt32 Read FRangeKM Write FRangeKM;
        Property SafetyRating: NullableString Read FSafetyRating Write FSafetyRating;
        Property BasePrice: NullableDouble Read FBasePrice Write FBasePrice;
        Property IsActive: NullableBoolean Read FIsActive Write FIsActive;
        Property IsSystemic: NullableBoolean Read FIsSystemic Write FIsSystemic;
        Property Description: NullableString Read FDescription Write FDescription;
        Property CreatedAt: NullableTDateTime Read FCreatedAt Write FCreatedAt;
    End;

Implementation

End.
