Unit Model.Contract.FileResultContract;

Interface

Uses
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    System.Generics.Collections;

Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('contacrt_contractfile')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TContract_FileResult = Class(TMVCActiveRecord)
    Private
        [MVCTableField('ContractFileID', [foPrimaryKey, foAutoGenerated])]
        FContractFileID: Int64;

        [MVCTableField('FileName')]
        FFileName: String;

        [MVCTableField('UploadedByUserID')]
        FUploadedByUserID: NullableInt32;

        [MVCTableField('UploadedAt', [foReadOnly])]
        FUploadedAt: TDateTime;

        [MVCTableField('FileSize')]
        FFileSize: NullableInt64;

        [MVCTableField('ErrorMessage')]
        FErrorMessage: NullableString;

        [MVCTableField('HasError_InsertRawData')]
        FHasError_InsertRawData: NullableBoolean;

        [MVCTableField('HasError_RunSP')]
        FHasError_RunSP: NullableBoolean;

    Public
        Property ContractFileID: Int64 Read FContractFileID Write FContractFileID;
        Property FileName: String Read FFileName Write FFileName;
        Property UploadedByUserID: NullableInt32 Read FUploadedByUserID Write FUploadedByUserID;
        Property UploadedAt: TDateTime Read FUploadedAt Write FUploadedAt;
        Property FileSize: NullableInt64 Read FFileSize Write FFileSize;
        Property ErrorMessage: NullableString Read FErrorMessage Write FErrorMessage;
        Property HasError_InsertRawData: NullableBoolean Read FHasError_InsertRawData Write FHasError_InsertRawData;
        Property HasError_RunSP: NullableBoolean Read FHasError_RunSP Write FHasError_RunSP;
    End;

Implementation

End.
