unit Model.ContractRaw;

interface

uses
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    System.Generics.Collections;

type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('contract_raw')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TContractRaw = class(TMVCActiveRecord)
    private
        [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
        FId: Int64;

        [MVCTableField('file_upload_id')]
        FFileUploadID: Int64;

        [MVCTableField('con')]
        Fcon: NullableString; // Contract_Number

        [MVCTableField('cdt')]
        Fcdt: NullableString; // Contract_Date

        [MVCTableField('cdg')]
        Fcdg: NullableString; // Contract_Date_Gregorian

        [MVCTableField('rqn')]
        Frqn: NullableString; // Request_Number

        [MVCTableField('rqd')]
        Frqd: NullableString; // Request_Date

        [MVCTableField('rdg')]
        Frdg: NullableString; // Request_Date_Gregorian

        [MVCTableField('cni')]
        Fcni: NullableString; // Customer_National_ID

        [MVCTableField('cnf')]
        Fcnf: NullableString; // Customer_Full_Name

        [MVCTableField('cty')]
        Fcty: NullableString; // Customer_Type

        [MVCTableField('ccy')]
        Fccy: NullableString; // Customer_City

        [MVCTableField('dcd')]
        Fdcd: NullableString; // Dealership_Code

        [MVCTableField('dnm')]
        Fdnm: NullableString; // Dealership_Name

        [MVCTableField('dcy')]
        Fdcy: NullableString; // Dealership_City

        [MVCTableField('dpr')]
        Fdpr: NullableString; // Dealership_Province

        [MVCTableField('vty')]
        Fvty: NullableString; // Vehicle_Type

        [MVCTableField('vcl')]
        Fvcl: NullableString; // Vehicle_Color

        [MVCTableField('ccd')]
        Fccd: NullableString; // Color_Code

        [MVCTableField('gtw')]
        Fgtw: NullableString; // Gateway

        [MVCTableField('reg')]
        Freg: NullableString; // Region

        [MVCTableField('sln')]
        Fsln: NullableString; // Sales_License_Number

        [MVCTableField('sld')]
        Fsld: NullableString; // Sales_License_Description

        [MVCTableField('pmd')]
        Fpmd: NullableString; // Payment_Method_Description

        [MVCTableField('dld')]
        Fdld: NullableString; // Delivery_Date

        [MVCTableField('ddd')]
        Fddd: NullableString; // Delivery_Due_Days

        [MVCTableField('acd')]
        Facd: NullableString; // Assignable_Chassis_10th_Digit

        [MVCTableField('chn')]
        Fchn: NullableString; // Chassis_Number

        [MVCTableField('dlm')]
        Fdlm: NullableString; // Delivery_Month

        [MVCTableField('ddc')]
        Fddc: NullableString; // Delivery_Dealership_Code

        [MVCTableField('ddn')]
        Fddn: NullableString; // Delivery_Dealership_Name

        [MVCTableField('dll')]
        Fdll: NullableString; // Delivery_Location

        [MVCTableField('vmd')]
        Fvmd: NullableString; // Vehicle_Model

        [MVCTableField('rds')]
        Frds: NullableString; // Registration_Documents_Delivery_Status

        [MVCTableField('fds')]
        Ffds: NullableString; // Final_Payment_Documents_Delivery_Status

        [MVCTableField('ins')]
        Fins: NullableString; // Invoice_Not_Issued_Status

        [MVCTableField('vds')]
        Fvds: NullableString; // Verification_Documents_Status

        [MVCTableField('chs')]
        Fchs: NullableString; // Chassis_Status

        [MVCTableField('ald')]
        Fald: NullableString; // Allocation_Date

        [MVCTableField('alg')]
        Falg: NullableString; // Allocation_Date_Gregorian

        [MVCTableField('pld')]
        Fpld: NullableString; // Plating_Date

        [MVCTableField('plg')]
        Fplg: NullableString; // Plating_Date_Gregorian

        [MVCTableField('pl1')]
        Fpl1: NullableString; // Plating_Date_Gregorian1

        [MVCTableField('dmd')]
        Fdmd: NullableString; // Document_Date

        [MVCTableField('dms')]
        Fdms: NullableString; // Document_Status

        [MVCTableField('pdd')]
        Fpdd: NullableString; // Physical_Delivery_Date

        [MVCTableField('pln')]
        Fpln: NullableString; // Plate_Number

        [MVCTableField('cnd')]
        Fcnd: NullableString; // Cancellation_Date

        [MVCTableField('cns')]
        Fcns: NullableString; // Contract_Status

        [MVCTableField('sly')]
        Fsly: NullableString; // Sale_Type

        [MVCTableField('cpd')]
        Fcpd: NullableString; // Customer_Payment_Date

        [MVCTableField('fpd')]
        Ffpd: NullableString; // Final_Payment_Date

        [MVCTableField('aad')]
        Faad: NullableString; // Accounting_Approval_Date

        [MVCTableField('pmc')]
        Fpmc: NullableString; // Payment_Method_Code

        [MVCTableField('inv')]
        Finv: NullableString; // Invitation_Number

        [MVCTableField('rts')]
        Frts: NullableString; // Request_Timestamp

        [MVCTableField('apr')]
        Fapr: NullableString; // Approved_Price

        [MVCTableField('prt')]
        Fprt: NullableString; // Price_Type

        [MVCTableField('gni')]
        Fgni: NullableString; // Guarantor_National_ID

        [MVCTableField('dma')]
        Fdma: NullableString; // Discount_Amount

        [MVCTableField('tar')]
        Ftar: NullableString; // Total_Amount_Received

        [MVCTableField('cft')]
        Fcft: NullableString; // Contract_Format_Type

        [MVCTableField('ani')]
        Fani: NullableString; // Assignor_National_ID

        [MVCTableField('ass')]
        Fass: NullableString; // Assignment_Status

        [MVCTableField('cst')]
        Fcst: NullableString; // Cancellation_Status

        [MVCTableField('org')]
        Forg: NullableString; // Organization

        [MVCTableField('knm')]
        Fknm: NullableString; // Kardex_Number

        [MVCTableField('kdt')]
        Fkdt: NullableString; // Kardex_Date

        [MVCTableField('cib')]
        Fcib: NullableString; // Cancellation_IBAN

        [MVCTableField('tca')]
        Ftca: NullableString; // Total_Checks_Amount

        [MVCTableField('noc')]
        Fnoc: NullableString; // Number_of_Checks

        [MVCTableField('rcu')]
        Frcu: NullableString; // Request_Creator_User

        [MVCTableField('dty')]
        Fdty: NullableString; // Document_Type

        [MVCTableField('icb')]
        Ficb: NullableString; // Is_Contract_Blacklisted

        [MVCTableField('icl')]
        Ficl: NullableString; // Is_Customer_Blacklisted

        [MVCTableField('pcd')]
        Fpcd: NullableString; // Postal_Code

        [MVCTableField('lii')]
        Flii: NullableString; // Last_Issued_Invitation

        [MVCTableField('lcp')]
        Flcp: NullableString; // Last_Completed_Payment_Invitation

        [MVCTableField('fsd')]
        Ffsd: NullableString; // First_Signature_Date

        [MVCTableField('fsg')]
        Ffsg: NullableString; // First_Signatory

        [MVCTableField('ssd')]
        Fssd: NullableString; // Second_Signature_Date

        [MVCTableField('ssg')]
        Fssg: NullableString; // Second_Signatory

        [MVCTableField('cob')]
        Fcob: NullableString; // Customer_Outstanding_Balance

        [MVCTableField('cca')]
        Fcca: NullableString; // Checks_Count_After_Kardex

        [MVCTableField('scd')]
        Fscd: NullableString; // Scrapping_Certificate_Date

        [MVCTableField('dda')]
        Fdda: NullableString; // Dealership_Address

    public
        property Id: Int64 read FId write FId;
        property FileUploadID: Int64 read FFileUploadID write FFileUploadID;

        property con: NullableString read Fcon write Fcon; // Contract_Number
        property cdt: NullableString read Fcdt write Fcdt; // Contract_Date
        property cdg: NullableString read Fcdg write Fcdg; // Contract_Date_Gregorian
        property rqn: NullableString read Frqn write Frqn; // Request_Number
        property rqd: NullableString read Frqd write Frqd; // Request_Date
        property rdg: NullableString read Frdg write Frdg; // Request_Date_Gregorian
        property cni: NullableString read Fcni write Fcni; // Customer_National_ID
        property cnf: NullableString read Fcnf write Fcnf; // Customer_Full_Name
        property cty: NullableString read Fcty write Fcty; // Customer_Type
        property ccy: NullableString read Fccy write Fccy; // Customer_City
        property dcd: NullableString read Fdcd write Fdcd; // Dealership_Code
        property dnm: NullableString read Fdnm write Fdnm; // Dealership_Name
        property dcy: NullableString read Fdcy write Fdcy; // Dealership_City
        property dpr: NullableString read Fdpr write Fdpr; // Dealership_Province
        property vty: NullableString read Fvty write Fvty; // Vehicle_Type
        property vcl: NullableString read Fvcl write Fvcl; // Vehicle_Color
        property ccd: NullableString read Fccd write Fccd; // Color_Code
        property gtw: NullableString read Fgtw write Fgtw; // Gateway
        property reg: NullableString read Freg write Freg; // Region
        property sln: NullableString read Fsln write Fsln; // Sales_License_Number
        property sld: NullableString read Fsld write Fsld; // Sales_License_Description
        property pmd: NullableString read Fpmd write Fpmd; // Payment_Method_Description
        property dld: NullableString read Fdld write Fdld; // Delivery_Date
        property ddd: NullableString read Fddd write Fddd; // Delivery_Due_Days
        property acd: NullableString read Facd write Facd; // Assignable_Chassis_10th_Digit
        property chn: NullableString read Fchn write Fchn; // Chassis_Number
        property dlm: NullableString read Fdlm write Fdlm; // Delivery_Month
        property ddc: NullableString read Fddc write Fddc; // Delivery_Dealership_Code
        property ddn: NullableString read Fddn write Fddn; // Delivery_Dealership_Name
        property dll: NullableString read Fdll write Fdll; // Delivery_Location
        property vmd: NullableString read Fvmd write Fvmd; // Vehicle_Model
        property rds: NullableString read Frds write Frds; // Registration_Documents_Delivery_Status
        property fds: NullableString read Ffds write Ffds; // Final_Payment_Documents_Delivery_Status
        property ins: NullableString read Fins write Fins; // Invoice_Not_Issued_Status
        property vds: NullableString read Fvds write Fvds; // Verification_Documents_Status
        property chs: NullableString read Fchs write Fchs; // Chassis_Status
        property ald: NullableString read Fald write Fald; // Allocation_Date
        property alg: NullableString read Falg write Falg; // Allocation_Date_Gregorian
        property pld: NullableString read Fpld write Fpld; // Plating_Date
        property plg: NullableString read Fplg write Fplg; // Plating_Date_Gregorian
        property pl1: NullableString read Fpl1 write Fpl1; // Plating_Date_Gregorian1
        property dmd: NullableString read Fdmd write Fdmd; // Document_Date
        property dms: NullableString read Fdms write Fdms; // Document_Status
        property pdd: NullableString read Fpdd write Fpdd; // Physical_Delivery_Date
        property pln: NullableString read Fpln write Fpln; // Plate_Number
        property cnd: NullableString read Fcnd write Fcnd; // Cancellation_Date
        property cns: NullableString read Fcns write Fcns; // Contract_Status
        property sly: NullableString read Fsly write Fsly; // Sale_Type
        property cpd: NullableString read Fcpd write Fcpd; // Customer_Payment_Date
        property fpd: NullableString read Ffpd write Ffpd; // Final_Payment_Date
        property aad: NullableString read Faad write Faad; // Accounting_Approval_Date
        property pmc: NullableString read Fpmc write Fpmc; // Payment_Method_Code
        property inv: NullableString read Finv write Finv; // Invitation_Number
        property rts: NullableString read Frts write Frts; // Request_Timestamp
        property apr: NullableString read Fapr write Fapr; // Approved_Price
        property prt: NullableString read Fprt write Fprt; // Price_Type
        property gni: NullableString read Fgni write Fgni; // Guarantor_National_ID
        property dma: NullableString read Fdma write Fdma; // Discount_Amount
        property tar: NullableString read Ftar write Ftar; // Total_Amount_Received
        property cft: NullableString read Fcft write Fcft; // Contract_Format_Type
        property ani: NullableString read Fani write Fani; // Assignor_National_ID
        property ass: NullableString read Fass write Fass; // Assignment_Status
        property cst: NullableString read Fcst write Fcst; // Cancellation_Status
        property org: NullableString read Forg write Forg; // Organization
        property knm: NullableString read Fknm write Fknm; // Kardex_Number
        property kdt: NullableString read Fkdt write Fkdt; // Kardex_Date
        property cib: NullableString read Fcib write Fcib; // Cancellation_IBAN
        property tca: NullableString read Ftca write Ftca; // Total_Checks_Amount
        property noc: NullableString read Fnoc write Fnoc; // Number_of_Checks
        property rcu: NullableString read Frcu write Frcu; // Request_Creator_User
        property dty: NullableString read Fdty write Fdty; // Document_Type
        property icb: NullableString read Ficb write Ficb; // Is_Contract_Blacklisted
        property icl: NullableString read Ficl write Ficl; // Is_Customer_Blacklisted
        property pcd: NullableString read Fpcd write Fpcd; // Postal_Code
        property lii: NullableString read Flii write Flii; // Last_Issued_Invitation
        property lcp: NullableString read Flcp write Flcp; // Last_Completed_Payment_Invitation
        property fsd: NullableString read Ffsd write Ffsd; // First_Signature_Date
        property fsg: NullableString read Ffsg write Ffsg; // First_Signatory
        property ssd: NullableString read Fssd write Fssd; // Second_Signature_Date
        property ssg: NullableString read Fssg write Fssg; // Second_Signatory
        property cob: NullableString read Fcob write Fcob; // Customer_Outstanding_Balance
        property cca: NullableString read Fcca write Fcca; // Checks_Count_After_Kardex
        property scd: NullableString read Fscd write Fscd; // Scrapping_Certificate_Date
        property dda: NullableString read Fdda write Fdda; // Dealership_Address
    end;

implementation

end.
