Unit Model.ResultCustomerContact;

Interface

Uses
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    System.Generics.Collections;

Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('lead_resultcontactcustomer_raw')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TLeadPlatformRaw = Class(TMVCActiveRecord)
    Private
        [MVCTableField('RawID', [foPrimaryKey, foAutoGenerated])]
        FRawID: Int64;

        [MVCTableField('FileUploadID')]
        FFileUploadID: Int64;

        [MVCTableField('phn')]
        Fphn: NullableString; // Phone Number

        [MVCTableField('fnm')]
        Ffnm: NullableString; // Full Name

        [MVCTableField('ncd')]
        Fncd: NullableString; // National Code

        [MVCTableField('rcr')]
        Frcr: NullableString; // Requested Car

        [MVCTableField('brn')]
        Fbrn: NullableString; // Branch

        [MVCTableField('agt')]
        Fagt: NullableString; // Calling Agent

        [MVCTableField('lcn')]
        Flcn: NullableString; // Last Contact Date

        [MVCTableField('scs')]
        Fscs: NullableString; // Status Change Steps

        [MVCTableField('cst')]
        Fcst: NullableString; // Customer Status

        [MVCTableField('ds1')]
        Fds1: NullableString; // Description 1

        [MVCTableField('ds2')]
        Fds2: NullableString; // Description 2

        [MVCTableField('ds3')]
        Fds3: NullableString; // Description 3

        [MVCTableField('ptn')]
        Fptn: NullableString; // Potential

        [MVCTableField('cch')]
        Fcch: NullableString; // Communication Channel

        [MVCTableField('cmp')]
        Fcmp: NullableString; // Campaign Name

    Public
        Property RawID: Int64 Read FRawID Write FRawID;
        Property FileUploadID: Int64 Read FFileUploadID Write FFileUploadID;

        Property phn: NullableString Read Fphn Write Fphn; // شماره تماس
        Property fnm: NullableString Read Ffnm Write Ffnm; // نام و نام خانوادگی
        Property ncd: NullableString Read Fncd Write Fncd; // کدملی
        Property rcr: NullableString Read Frcr Write Frcr; // خودرو درخواستی
        Property brn: NullableString Read Fbrn Write Fbrn; // شعبه
        Property agt: NullableString Read Fagt Write Fagt; // کارشناس تماس گیرنده
        Property lcn: NullableString Read Flcn Write Flcn; // آخرین تماس
        Property scs: NullableString Read Fscs Write Fscs; // مراحل تغییر حالت
        Property cst: NullableString Read Fcst Write Fcst; // وضعیت مشتری
        Property ds1: NullableString Read Fds1 Write Fds1; // توضیحات 1
        Property ds2: NullableString Read Fds2 Write Fds2; // توضیحات 2
        Property ds3: NullableString Read Fds3 Write Fds3; // توضیحات 3
        Property ptn: NullableString Read Fptn Write Fptn; // پتانسیل مشتری شدن
        Property cch: NullableString Read Fcch Write Fcch; // راه ارتباطی با مجموعه
        Property cmp: NullableString Read Fcmp Write Fcmp; // نام کمپین
    End;

Implementation

End.
