Unit Model.Document;

Interface

Uses
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    MVCFramework.ActiveRecord;

Type
    [MVCNameCase(ncCamelCase)]
    [MVCTable('documents')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TDocument = Class(TMVCActiveRecord)
    Private
        [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
        fID: Int32;

        [MVCTableField('entity_type')]
        fEntityType: NullableString; // enum('customer','contract','interaction')

        [MVCTableField('entity_id')]
        fEntityID: NullableInt32;

        [MVCTableField('document_type')]
        fDocumentType: NullableString;

        [MVCTableField('file_name')]
        fFileName: NullableString;

        [MVCTableField('file_path')]
        fFilePath: NullableString;

        [MVCTableField('file_size')]
        fFileSize: NullableInt32;

        [MVCTableField('file_type')]
        fFileType: NullableString;

        [MVCTableField('uploaded_by')]
        fUploadedBy: NullableInt32;

        [MVCTableField('uploaded_at', [foReadOnly])]
        fUploadedAt: NullableString;

        [MVCTableField('description')]
        fDescription: NullableString;

    Public
        property ID: Int32 read fID write fID;
        property EntityType: NullableString read fEntityType write fEntityType;
        property EntityID: NullableInt32 read fEntityID write fEntityID;
        property DocumentType: NullableString read fDocumentType write fDocumentType;
        property FileName: NullableString read fFileName write fFileName;
        property FilePath: NullableString read fFilePath write fFilePath;
        property FileSize: NullableInt32 read fFileSize write fFileSize;
        property FileType: NullableString read fFileType write fFileType;
        property UploadedBy: NullableInt32 read fUploadedBy write fUploadedBy;
        property UploadedAt: NullableString read fUploadedAt write fUploadedAt;
        property Description: NullableString read fDescription write fDescription;
    End;

Implementation

End.
