Unit Model.Customer.Assignment;

Interface

Uses
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons;

Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('customer_assignment')]
    [MVCEntityActions([eaRetrieve, eaCreate, eaUpdate, eaDelete])]
    TCustomer_Assignment = Class(TMVCActiveRecord)
    Private
        [MVCTableField('AssignmentID', [foPrimaryKey, foAutoGenerated])]
        FAssignmentID: Int64;

        [MVCTableField('Phone')]
        FPhone: String;

        [MVCTableField('BranchID')]
        FBranchID: Int32;

        [MVCTableField('SourceCollectingDataID')]
        FSourceCollectingDataID: Int32;

        [MVCTableField('UserName')]
        FUserName: NullableString;

    Public
        Property AssignmentID: Int64 Read FAssignmentID Write FAssignmentID;
        Property Phone: String Read FPhone Write FPhone;
        Property BranchID: Int32 Read FBranchID Write FBranchID;
        Property SourceCollectingDataID: Int32 Read FSourceCollectingDataID Write FSourceCollectingDataID;
        Property UserName: NullableString Read FUserName Write FUserName;
    End;

Implementation

End.

